name: "Experimental Release"

concurrency: experimental-release

on:
  push:
    branches:
      - main
    paths-ignore: [docs/**, scripts/**, "**.md", "**.mdx"]

jobs:
  build-windows:
    uses: ./.github/workflows/build.yml
    with:
      artifact: windows-tiles-x64-msvc
      os: windows-latest
      arch: x64
      ext: zip
      content-type: application/zip
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-linux-tiles:
    uses: ./.github/workflows/build.yml
    with:
      artifact: linux-tiles-x64
      os: ubuntu-latest
      tiles: 1
      sound: 1
      ext: tar.gz
      content-type: application/gzip
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-linux-curses:
    uses: ./.github/workflows/build.yml
    with:
      artifact: linux-curses-x64
      os: ubuntu-latest
      tiles: 0
      sound: 0
      ext: tar.gz
      content-type: application/gzip
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-osx-curses-x64:
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-curses-x64
      os: macos-15-intel
      tiles: 0
      sound: 0
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-osx-tiles-x64:
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-tiles-x64
      os: macos-15-intel
      tiles: 1
      sound: 1
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-osx-curses-arm:
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-curses-arm
      os: macos-15
      tiles: 0
      sound: 0
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-osx-tiles-arm:
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-tiles-arm
      os: macos-15
      tiles: 1
      sound: 1
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-android-x64:
    uses: ./.github/workflows/build.yml
    with:
      artifact: android-x64
      os: ubuntu-latest
      android: arm64
      ext: apk
      content-type: application/apk
      version-label: experimental
      upload-to-release: true
    secrets: inherit

  build-android-bundle:
    uses: ./.github/workflows/build.yml
    with:
      artifact: android-bundle
      os: ubuntu-latest
      android: bundle
      ext: aab
      content-type: application/aap
      version-label: experimental
      upload-to-release: true
    secrets: inherit
