name: Validate translation template extraction

on:
  pull_request:
    paths:
      - "src/**/*.cpp"
      - "lang/bn_extract_json_strings.sh"
      - "scripts/extract_json_strings.ts"
      - "scripts/extract_json_strings_test.ts"
      - "scripts/testdata/extract_json_strings/**"
      - "deno.jsonc"
      - "deno.lock"
      - "build-scripts/requirements.sh"

# We only care about the latest revision of a PR, so cancel previous instances.
concurrency:
  group: i18n-extraction-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  check-extraction:
    runs-on: ubuntu-slim
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gettext

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with: { cache: true }

      - name: Check that translation template extraction works
        run: lang/update_pot.sh
