name: Code Style Check

on:
  pull_request:
    paths: ["**.json", "**.cpp", "**.hpp", "**.h", "**.c"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: sudo apt-get install astyle
      - run: make astyle
      - run: make style-all-json-parallel RELEASE=1

      - uses: reviewdog/action-suggester@v1
        if: ${{ always() }}
        with:
          tool_name: astyle, style-json
