name: "Manual release"
concurrency: release

on:
  workflow_dispatch:
    inputs:
      major:
        { description: SemVer major, required: true, type: number, default: 0 }
      minor: { description: SemVer minor, required: true, type: number }
      patch:
        { description: SemVer patch, required: true, type: number, default: 0 }

env:
  VERSION: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Create release
        run: |
          set +e
          gh release view ${{ env.VERSION }} --json name --jq '.name'
          HAS_NO_RELEASE=$? # error == exitcode 1 == no release of given version exists
          if (( $HAS_NO_RELEASE == 0 )); then
            echo "Release already exists, skipping." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "Release does not exist, creating a new one" >> "$GITHUB_STEP_SUMMARY"
            gh release create ${{ env.VERSION }} \
              --title "Cataclysm-BN ${{ env.VERSION }}" \
              --draft \
              --prerelease \
              --generate-notes \
              --target ${{ github.sha }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: windows-tiles-x64-msvc
      os: windows-latest
      arch: x64
      ext: zip
      content-type: application/zip
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-linux-tiles:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: linux-tiles-x64
      os: ubuntu-latest
      tiles: 1
      sound: 1
      ext: tar.gz
      content-type: application/gzip
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-linux-curses:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: linux-curses-x64
      os: ubuntu-latest
      tiles: 0
      sound: 0
      ext: tar.gz
      content-type: application/gzip
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-osx-curses-x64:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-curses-x64
      os: macos-15-intel
      tiles: 0
      sound: 0
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-osx-tiles-x64:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-tiles-x64
      os: macos-15-intel
      tiles: 1
      sound: 1
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-osx-curses-arm:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-curses-arm
      os: macos-15
      tiles: 0
      sound: 0
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-osx-tiles-arm:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: osx-tiles-arm
      os: macos-15
      tiles: 1
      sound: 1
      ext: dmg
      content-type: application/x-apple-diskimage
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-android-x64:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: android-x64
      os: ubuntu-latest
      android: arm64
      ext: apk
      content-type: application/apk
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit

  build-android-bundle:
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      artifact: android-bundle
      os: ubuntu-latest
      android: bundle
      ext: aab
      content-type: application/aap
      version-label: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
      upload-to-release: true
      release-tag: "v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"
    secrets: inherit
