name: "Cataclysm OSX Manual Build"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "build-data/osx/**"
      - "docs/**"
      - "doxygen_doc/**"
      - "gfx/**"
      - "lang/**"
      - "lgtm/**"
      - "tools/**"
      - "!tools/format/**"
      - "utilities/**"
      - "scripts/**"
      - "**.md"
      - "**.mdx"
# We only care about the latest revision of a PR, so cancel previous instances.
concurrency:
  group: osx-build-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_catatclysm:
    if: github.event.pull_request.draft == false

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: osx-curses-x64
            os: macos-15-intel
            tiles: 0
            cmake_arch: x86_64
            artifact: osx-curses-x64
            ext: dmg
            content: application/x-apple-diskimage
          - name: osx-tiles-x64
            os: macos-15-intel
            tiles: 1
            cmake_arch: x86_64
            artifact: osx-tiles-x64
            ext: dmg
            content: application/x-apple-diskimage
          - name: osx-curses-arm
            os: macos-15
            tiles: 0
            cmake_arch: arm64
            artifact: osx-curses-arm
            ext: dmg
            content: application/x-apple-diskimage
          - name: osx-tiles-arm
            os: macos-15
            tiles: 1
            cmake_arch: arm64
            artifact: osx-tiles-arm
            ext: dmg
            content: application/x-apple-diskimage
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      ZSTD_CLEVEL: 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install build dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=yes HOMEBREW_NO_INSTALL_CLEANUP=yes brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gettext parallel llvm@20 astyle sqlite3 zlib cmake ninja
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip3 install mac_alias==2.2.0 dmgbuild==1.6.1 biplist polib luaparser

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.artifact }}-${{ github.ref_name }}
          restore-keys: |
            ${{ matrix.artifact }}-${{ github.ref_name }}
            ${{ matrix.artifact }}-main
            ${{ matrix.artifact }}-
          max-size: 500M
          verbose: 2
          save: ${{ github.event_name != 'pull_request' }}

      - name: Check Clang OK
        run: |
          echo "Clang++ version:"
          $(brew --prefix llvm@20)/bin/clang++ --version  # Ensure clang++ is installed and working

      - name: Build
        run: |
          source ./venv/bin/activate
          cmake -G Ninja \
            -S "${{ github.workspace }}" \
            -B "${{ github.workspace }}/build" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=$(brew --prefix llvm@20)/bin/clang \
            -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@20)/bin/clang++ \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.cmake_arch }} \
            -DTILES=${{ matrix.tiles == 1 && 'ON' || 'OFF' }} \
            -DCURSES=${{ matrix.tiles == 1 && 'OFF' || 'ON' }} \
            -DSOUND=${{ matrix.tiles == 1 && 'ON' || 'OFF' }} \
            -DTESTS=OFF \
            -DLANGUAGES=all \
            -DUSE_HOME_DIR=ON \
            -DUSE_PREFIX_DATA_DIR=OFF \
            -DBACKTRACE=OFF \
            -DJSON_FORMAT=OFF
          cmake --build "${{ github.workspace }}/build" --target package-dmg --parallel 3
